In [29]:
import pandas as pd

In [30]:
df=pd.read_csv("lawsikho_table_2.csv")

In [31]:
df.head()

,IPC_Section,Offence,BNS_Section,What Changed
0,302,Murder (punishment),103(1),BNS 103(2) adds mob lynching as an aggravated ...
1,304,Culpable homicide not amounting to murder (pun...,105,Renumbered. Punishment structure largely retai...
2,304A,Death by negligence,106,BNS 106(2) adds an aggravated category for dea...
3,304B,Dowry death,80,Renumbered. Now appears under offences against...
4,307,Attempt to murder,109,"Renumbered. Punishment structure unchanged, li..."

In [32]:
df=df[['IPC_Section','BNS_Section']]

In [33]:
df.head()

  IPC_Section BNS_Section
0         302      103(1)
1         304         105
2        304A         106
3        304B          80
4         307         109

In [34]:
df1=pd.read_csv("lawsikho_table_1.csv")

In [35]:
df1.head()

  IPC_Section  BNS_Section
0         302          103
1         307          109
2        304B           80
3         376          64
4         354           74

In [36]:

merged = pd.merge(
    df,
    df1,
    on='BNS_Section',
    how='outer',
    suffixes=('_df1', '_df2')
)

In [37]:
print(merged)

         IPC_Section BNS_Section IPC_Section
0                299         100          NaN
1                300         101          NaN
2                NaN         103         302
3                NaN         103          302
4                302      103(1)          NaN
..               ...         ...          ...
77            103(2)         NaN          NaN
78               111         NaN          NaN
79               112         NaN          NaN
80               113         NaN          NaN
81  Various sections         NaN          NaN

[82 rows x 3 columns]

In [38]:
merged.drop_duplicates(inplace=True)

In [39]:
print(merged)

         IPC_Section BNS_Section IPC_Section
0                299         100          NaN
1                300         101          NaN
2                NaN         103         302
3                NaN         103          302
4                302      103(1)          NaN
..               ...         ...          ...
77            103(2)         NaN          NaN
78               111         NaN          NaN
79               112         NaN          NaN
80               113         NaN          NaN
81  Various sections         NaN          NaN

[77 rows x 3 columns]